### ISSUE TITLE
How to Build And Run the Repository

### ISSUE THREAD

**Issue by LuanDalOrto** [singnet/opencog-docker#17]
Hi There, my name is Luan, and I want to know how can I build and run the repository, 
I 'm interested in running the Eva-Opencog, because is the full package with the chatbot, If It's not possible to compile It I will have no choice And my secondary option will be to try the Eva-Owyl, but There Will be no chatbot, And the last thing I need help is I want to know which is the best version of Ubuntu to run And avoid errors,I'm running Ubuntu in a virtualbox virtual machine ok Windows 10 Running .Thanks.

**Comment by LuanDalOrto** [comment]
It is giving an error when trying to build-all.sh or build-old.sh saying something like "It has built incomplete with some errors"

**Comment by amebel** [comment]
Eva-* images are not being maintained. Most of the images defined at https://github.com/singnet/opencog-docker/tree/master/opencog are maintained and you can find them at https://hub.docker.com/u/singnet . 

With regards to chatbot see https://github.com/singnet/opencog/tree/master/examples/ghost

**Comment by LuanDalOrto** [comment]
Thanks. I´ll try to use this one. I tried on the Hanson Robotics Repository also but it´s hard to run.
